#!/bin/sh

node=$1

if [ ! -e services/redis-1-master.service ]; then
	echo 'error: services/redis-1-master.service does not exist (check working directory?)' 1>&2
	exit 1
fi

units=$(fleetctl list-units --no-legend)
machines=$(echo "$units" | sed -n -e 's,^.*\(........\)\.\.\./.*,\1,p' | sort | uniq)

if ! echo "$machines" | grep -q "^$node$"; then
	echo error: node "'$node'" must be one of $machines 1>&2
	exit 1
fi

if echo "$units" | grep -q redis-1-master.service.*$node; then
	echo error: redis-1-maser already running on node "'$node'" 1>&2
	exit 1
fi

slaves=$(echo "$units" | grep redis-1-slave-.*$node | awk '{print $1}')
for i in $slaves; do
	slave_files="$slave_files services/$i"
done

cat services/redis-1-master.service > redis-1-master.service || exit 1
echo X-ConditionMachineID=$node >> redis-1-master.service

fleetctl destroy redis-1-master.service $slaves
fleetctl start redis-1-master.service $slave_files
fleetctl list-units | grep ^redis-1-
