#!/bin/sh

for i in redis-1-master \
	 redis-1-slave-2 \
	 redis-1-slave-2-amb-master \
	 redis-1-slave-1 \
	 redis-1-slave-1-amb-master; do
    fleetctl stop services/$i.service
    fleetctl unload services/$i.service
    fleetctl destroy services/$i.service
done
